// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
/// 
/// 


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEwqmUCXUn7dneI_y-2DrWjdr-qc0rGM',
    appId: '1:677267039930:web:b32fb893c8cfe7820d0483',
    messagingSenderId: '677267039930',
    projectId: 'shopmitra-4f135',
    authDomain: 'shopmitra-4f135.firebaseapp.com',
    storageBucket: 'shopmitra-4f135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFgQ8Uqs7gecuDLD2jpXD2mEUVoQ33fo',
    appId: '1:677267039930:android:124745fa1fc730270d0483',
    messagingSenderId: '677267039930',
    projectId: 'shopmitra-4f135',
    storageBucket: 'shopmitra-4f135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1j7GOI6uIH_8L-oF7X-OIx2g2dh-OXo',
    appId: '1:677267039930:ios:94c82b5a5bf9bb790d0483',
    messagingSenderId: '677267039930',
    projectId: 'shopmitra-4f135',
    storageBucket: 'shopmitra-4f135.appspot.com',
    iosBundleId: 'com.example.crmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1j7GOI6uIH_8L-oF7X-OIx2g2dh-OXo',
    appId: '1:677267039930:ios:2640ae8a4efabba90d0483',
    messagingSenderId: '677267039930',
    projectId: 'shopmitra-4f135',
    storageBucket: 'shopmitra-4f135.appspot.com',
    iosBundleId: 'com.example.crmapp.RunnerTests',
  );
}


